export const QUERY_KEYS = {
  ME: ["me"],
  LOCATION: ["coords"],
  STORES: ({ page, keyword, sorting, categoryId }) => [
    "stores",
    page,
    keyword,
    sorting,
    categoryId,
  ],
  STORE_DETAIL: (storeId) => ["store", storeId],
  DIBS: ["dibs"],
  MENU_DETAIL: (menuId) => ["menuDetail", menuId],
  CART_DETAIL: (menuId) => ["cartDetail", menuId],
  REVIEWS: (page) => ["storeReviews", page],
  OWNER_STORE_REVIEWS: ["ownerStoreReviews"],
  STORE_REVIEWS: (storeId, page) => ["reviews", storeId, page],
  CART: ["cart"],
  USER: ["user"],
  ORDER: ["order"],
  ORDERS: (page) => ["orders", page],
  MENU_CATEGORY: ["menuCategory"],
  MENU_OPTION: ["menuOption"],
  OWNER_MENUS: ["ownerMenus"],
  OWNER_MENU: ["ownerMenu"],
};
