name: Frontend Deploy

on:
  push:
    paths:
      - 'front-end/**'
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production
        run: |
          echo "REACT_APP_API=${{ secrets.REACT_APP_API }}" >> .env.production
          echo "REACT_APP_KAKAO_API=${{ secrets.REACT_APP_KAKAO_API }}" >> .env.production
        shell: bash

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync build/ s3://god-of-delivery-bucket --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
